/**
 * @module main/bi/bi-report-builder
 *
 * Save-time template builder. Given a finished dashboard (hardcoded data) plus
 * the MCP/SQL tool calls that produced it, it asks the LLM ONCE to convert the
 * dashboard into a refreshable template:
 *   - params[]        : the variables a user can change (e.g. year, company)
 *   - queries[]       : the MCP calls per chart, with {{param}} placeholders
 *   - shellHtml       : the dashboard rewritten to read window.__REPORT_DATA__
 *                       (keyed by query.resultKey) instead of hardcoded values
 *
 * For AI reports the shell also contains an element with id="ai-recommendation"
 * whose text is regenerated by the LLM on each refresh from the fresh data.
 *
 * Run time stays LLM-free for BI; AI uses one extra call only for the
 * recommendation text. Returns null on failure so the caller can fall back to a
 * plain snapshot.
 */
import { runPiAiOneShot } from '../claude/claude-sdk-one-shot';
import { configStore } from '../config/config-store';
import { log, logError } from '../utils/logger';
import type { BIReportParam, BIReportQuery } from '../../shared/bi-report';

export interface BuiltTemplate {
  params: BIReportParam[];
  queries: BIReportQuery[];
  shellHtml: string;
}

const SYSTEM_PROMPT = `You convert a finished HTML dashboard into a REFRESHABLE TEMPLATE.

You receive:
- The dashboard HTML (with hardcoded numbers / chart data / table rows).
- The MCP tool calls (server, tool, args) that fetched the data.
- Whether this is an "AI" report (needs an AI recommendation slot) or a "BI" report.

Produce STRICT JSON ONLY (no markdown fences), with this exact shape:
{
  "params": [ { "name": "snake_case", "label": "Human label", "type": "text|number|date|select", "default": "value", "options": ["..."] } ],
  "queries": [ { "server": "...", "tool": "...", "argsTemplate": { ... }, "resultKey": "snake_case" } ],
  "shellHtml": "<full dashboard HTML rewritten to be data-driven>"
}

Rules:
1. params: the filters a user would change to re-run (year, month, company, region...). If the tool args contain such concrete filter values, replace them in argsTemplate with "{{param_name}}" and add a matching param. If there are no obvious filters, params = [].
2. queries: one per data set the dashboard shows. Keep the SAME server/tool as the input calls. resultKey is a stable key.
3. shellHtml: keep ALL layout, CSS and chart libraries. But every chart dataset and table body that came from data MUST be built at runtime from a global object window.__REPORT_DATA__ (keyed by the query resultKey) instead of hardcoded literals. Add a small script that reads window.__REPORT_DATA__ and renders the charts/tables. Do NOT hardcode the numbers anymore.
4. If isAi is true, include exactly one element <div id="ai-recommendation"></div> where the AI assessment will be injected at refresh; remove any stale hardcoded assessment text from that spot.
5. Output ONLY the JSON object.`;

function tryExtractJson(text: string): unknown | null {
  // The model may wrap JSON in prose or fences; extract the outermost object.
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = (fenced ? fenced[1] : text).trim();
  const start = candidate.indexOf('{');
  const end = candidate.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) return null;
  try {
    return JSON.parse(candidate.slice(start, end + 1));
  } catch {
    return null;
  }
}

export async function buildReportTemplate(opts: {
  html: string;
  capturedQueries: BIReportQuery[];
  isAi: boolean;
}): Promise<BuiltTemplate | null> {
  try {
    const config = configStore.getAll();
    const userPrompt = [
      `isAi: ${opts.isAi}`,
      '',
      'MCP tool calls captured from the session (JSON):',
      JSON.stringify(opts.capturedQueries, null, 2),
      '',
      'Dashboard HTML:',
      opts.html,
    ].join('\n');

    const { text } = await runPiAiOneShot(userPrompt, SYSTEM_PROMPT, config, {
      temperature: 0,
      maxTokens: 16000,
    });

    const parsed = tryExtractJson(text) as Partial<BuiltTemplate> | null;
    if (!parsed || typeof parsed.shellHtml !== 'string' || !parsed.shellHtml.trim()) {
      logError('[BIReport] builder returned no usable shellHtml');
      return null;
    }
    log('[BIReport] template built:', {
      params: parsed.params?.length ?? 0,
      queries: parsed.queries?.length ?? 0,
    });
    return {
      params: Array.isArray(parsed.params) ? (parsed.params as BIReportParam[]) : [],
      queries:
        Array.isArray(parsed.queries) && parsed.queries.length > 0
          ? (parsed.queries as BIReportQuery[])
          : opts.capturedQueries,
      shellHtml: parsed.shellHtml,
    };
  } catch (error) {
    logError('[BIReport] buildReportTemplate failed:', error);
    return null;
  }
}
